# Generated by Django 4.1.3 on 2022-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('Country', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pays',
            },
        ),
    ]
