# Generated by Django 4.1.3 on 2022-12-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Details_commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
            ],
            options={
                'db_table': 'details_commande',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pays',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'produit',
            },
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(fields=('stock_code',), name='stock_code unique'),
        ),
        migrations.AddConstraint(
            model_name='pays',
            constraint=models.UniqueConstraint(fields=('country',), name='country unique'),
        ),
        migrations.AddField(
            model_name='details_commande',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.commande'),
        ),
        migrations.AddField(
            model_name='details_commande',
            name='stock_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.produit'),
        ),
        migrations.AddField(
            model_name='commande',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.pays'),
        ),
        migrations.AlterUniqueTogether(
            name='details_commande',
            unique_together={('invoice_no', 'stock_code')},
        ),
        migrations.AddConstraint(
            model_name='commande',
            constraint=models.UniqueConstraint(fields=('invoice_no',), name='invoice_no unique'),
        ),
    ]
