# Generated by Django 4.1.3 on 2022-12-08 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('InvoiceNo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.pays')),
            ],
            options={
                'db_table': 'commande',
            },
        ),
    ]
