# Generated by Django 4.1.3 on 2022-12-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('StockCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'produit',
            },
        ),
    ]
