# Generated by Django 4.1.3 on 2022-12-08 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details_commande',
            fields=[
                ('id_details_commande', models.BigAutoField(primary_key=True, serialize=False)),
                ('InvoiceDate', models.DateField()),
                ('InvoiceNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.commande')),
                ('StockCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.produit')),
            ],
            options={
                'db_table': 'details_commande',
            },
        ),
    ]
