# Generated by Django 4.1.3 on 2022-12-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_alter_details_commande_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pays',
            old_name='Country',
            new_name='country',
        ),
    ]
