# Generated by Django 4.1.3 on 2022-12-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_rename_country_pays_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='InvoiceNo',
            new_name='invoice_no',
        ),
    ]
