# Generated by Django 4.1.3 on 2022-12-08 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_rename_country_commande_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='StockCode',
            new_name='stock_code',
        ),
    ]
