# Generated by Django 4.1.3 on 2022-12-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0008_rename_stockcode_produit_stock_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details_commande',
            old_name='InvoiceDate',
            new_name='invoice_date',
        ),
        migrations.RenameField(
            model_name='details_commande',
            old_name='InvoiceNo',
            new_name='invoice_no',
        ),
        migrations.RenameField(
            model_name='details_commande',
            old_name='StockCode',
            new_name='stock_code',
        ),
        migrations.AlterUniqueTogether(
            name='details_commande',
            unique_together={('invoice_no', 'stock_code')},
        ),
    ]
